### ISSUE TITLE
Error: undefined method 'modification_time' for Kemal::StaticFileHandler (Crystal 1.6.0)

### ISSUE THREAD

**Issue by petr-fischer** [kemalcr/kemal#649] opened 2022-10-07 22:50 UTC
Hello, latest kemal (1.2.0) started to complain something about `Kemal::StaticFileHandler`, I am lost a little...

```bash
# --- strip ---

In /usr/share/crystal/src/http/server/handler.cr:28:20

 28 | next_handler.call(context)
                   ^---
Error: instantiating '(HTTP::Handler | Proc(HTTP::Server::Context, Nil))#call(HTTP::Server::Context)'


In lib/kemal/src/kemal/static_file_handler.cr:51:27

 51 | last_modified = modification_time(file_path)
                      ^----------------
Error: undefined method 'modification_time' for Kemal::StaticFileHandler
```

**Comment by Blacksmoke16** [comment] 2022-10-07 23:59
Duplicate of #648 and #643

**Closed** 2022-10-08 00:17 UTC

**Comment by straight-shoota** [comment] 2022-10-08 11:14
This is fixed on master, just not released yet.
@sdogruyol We need a release for compatibility with 1.6.0.
