### ISSUE TITLE
Cannot run example code

### ISSUE THREAD

**Issue by RubenBrocke** [kemalcr/kemal#425] opened 2017-11-28 19:46 UTC
### Description

I am unable to reproduce the example on your website due to an error

### Steps to Reproduce

1. Copy the example
2. Run the code using crystal run server.cr

**Expected behavior:** 
Getting this message:
[development] Kemal is ready to lead at http://0.0.0.0:3000
2015-12-01 13:47:48 +0200 | 200 | GET / - (666µs)

**Actual behavior:** [What actually happens]
Getting this message:
```
Kemal.run
      ^~~

in lib/kemal/src/kemal.cr:11: instantiating 'run(Nil)'

  def self.run(port = nil)
  ^

in lib/kemal/src/kemal.cr:12: instantiating 'Kemal:Module#run(Nil)'

    self.run port do
         ^~~

in lib/kemal/src/kemal.cr:55: instantiating 'send_file(HTTP::Server::Context, String)'

          send_file env, file_path
          ^~~~~~~~~

in lib/kemal/src/kemal/helpers/helpers.cr:100: instantiating 'File:Class#open(String)'

  File.open(file_path) do |file|
       ^~~~

in lib/kemal/src/kemal/helpers/helpers.cr:100: instantiating 'File:Class#open(String)'

  File.open(file_path) do |file|
       ^~~~

in lib/kemal/src/kemal/helpers/helpers.cr:111: 'Flate::Writer.new' is not expected to be invoked with a block, but a block was given

      Flate::Writer.new(env.response) do |deflate|
                    ^~~

```

### Versions

Happens on version 0.21.0 of kemal

**Comment by straight-shoota** [comment] 2017-11-28 20:03
It seems you're not using the Kemal 0.21 release but the current master branch which is only working on Crystal 0.24 (not yet officially released).

Duplicate of #422

**Closed** 2017-11-30 16:28 UTC
