### ISSUE TITLE
Compilation issue with crystal 1.6

### ISSUE THREAD

**Issue by waghanza** [kemalcr/kemal#650] opened 2022-10-08 13:02 UTC
With the following command `shards build --release --no-debug --static`, I have a compilation issue
```crystal
Error target server failed to compile:
Showing last frame. Use --error-trace for full trace.

In lib/kemal/src/kemal/static_file_handler.cr:51:27

 51 | last_modified = modification_time(file_path)
                      ^----------------
Error: undefined method 'modification_time' for Kemal::StaticFileHandler
```

Source is https://github.com/the-benchmarker/web-frameworks/blob/013fbc9fc6966052ee98fc2e4749f3753d3f1b83/crystal/kemal/src/server.cr#L1

I try to compile inside a container based on **alpine**

```dockerfile
FROM crystallang/crystal:1.6.0-alpine

WORKDIR /usr/src/app

COPY . ./

RUN apk add --update yaml-static


RUN shards lock
RUN shards install --production
RUN shards build --release --no-debug --static

FROM alpine

COPY --from=0 /usr/src/app/bin/server /usr/bin/app



WORKDIR /usr/bin
CMD ./app
```

**Comment by Blacksmoke16** [comment] 2022-10-08 14:07
Duplicate of #649, #648, and #643

**Comment by guanting112** [comment] 2022-10-08 21:17
try this:

```yaml
dependencies:
  kemal:
    github: kemalcr/kemal
    branch: master
```

![kemal](https://user-images.githubusercontent.com/11306350/194728019-a8f21629-62e0-4fcc-adf7-cd5e9552daf3.png)

**Comment by sdogruyol** [comment] 2022-10-09 10:46
I'll cut a release in the upcoming hours 👍

**Comment by sdogruyol** [comment] 2022-10-09 10:55
Here we go https://github.com/kemalcr/kemal/releases/tag/v1.3.0 🚀

**Closed by sdogruyol** 2022-10-09 10:55 UTC
